#!/usr/bin/env ansible-playbook
- hosts: all
  tasks:
   - name: Benchmark Disk
     script: ./DiskBench.sh
     register: results
   - name: Benchmark To File
     local_action: copy content="{{results.stdout}}" dest="./results/{{ansible_nodename}}.DiskBench"
