#!/usr/bin/env ansible-playbook
- hosts: all
  tasks:
   - name: Copy Benchmark
     command: npm i greenfox1505/ZombieJerky.Net-Benchmark
   - name: Run Benchmark
     command: ./node_modules/.bin/AnsibleBenchmark
     register: results
   - name: Benchmark To File
     local_action: copy content="{{results.stdout}}" dest="./results/{{ansible_nodename}}.JSbench1"
   - name: Remove Benchmark
     command: npm r greenfox1505/ZombieJerky.Net-Benchmark
