#!/usr/bin/env ansible-playbook
---
- hosts: all
  tasks:
   - name: Upgrade
     apt:
       upgrade: dist
   - name: Install Test Suite
     apt:
       name: [ nodejs, npm, git, iperf3 ]
       state: installed
   - name: Install Ryan's Favs
     apt:
       name: [ byobu , htop , openjdk-8-jre , gcc , g++ , nodejs, npm, git, iperf3 , nano ]
       state: installed

  vars_prompt:
   - name: "ansible_sudo_pass"
     prompt: "Sudo password"
     private: yes
  become: true
